config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :absences
    resources :bank_holidays
    resources :employees
    resources :employee_factors
    resources :employee_allowances

    root to: 'employees#index'
  end

  get 'capacities/show'
  root to: 'capacities#show'
end

app/controllers/capacities_controller.rb
# frozen_string_literal: true

class CapacitiesController < ApplicationController
  JAN = :jan
  FEB = :feb
  MAR = :mar
  APR = :apr
  MAY = :may
  JUN = :jun
  JUL = :jul
  AUG = :aug
  SEP = :sep
  OCT = :oct
  NOV = :nov
  DEC = :dec
  MONTH_NAMES = [JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC].freeze

  def show
    the_year = Date.current.year
    @current_month = Date.current.month
    @month_names = MONTH_NAMES
    @bank_holidays = BankHoliday.where(year: the_year).map(&:calendar_date)
    @employees = Employee.includes(:employee_factors, :employee_allowances, :absences).all
    capacity_calculator = CapacityCalculator.new(@bank_holidays)

    dates = (1..12).map do |month|
      start_date = Date.new(the_year, month, 1)
      [start_date, start_date.end_of_month]
    end

    @employees_engineering_days = []
    @holiday_remainings = 0
    @employees.map do |employee|
      employee_engineering_days = [employee.name]
      dates.each do |start_date, end_date|
        engineering_days = capacity_calculator.get_employee_engineering_days_between(employee, start_date, end_date)
        employee_engineering_days << engineering_days
      end

      @holiday_remainings += employee.holiday_remaining_in_year(the_year)
      @employees_engineering_days << employee_engineering_days
    end

    # dynamic table
    @dynamic_start_date = params[:start_date].present? ? Date.parse(params[:start_date]) : Date.current
    @dynamic_end_date = params[:end_date].present? ? Date.parse(params[:end_date]) : Date.current.end_of_year
    @dynamic_team = params[:team]&.downcase 
    @dynamic_employees_engineering_days = []
    @employees.each do |employee|
      next if @dynamic_team.present? && employee.team.downcase != @dynamic_team

      employee_engineering_days = [employee.name]
      engineering_days = capacity_calculator.get_employee_engineering_days_between(employee, @dynamic_start_date,
                                                                                   @dynamic_end_date)
      holiday_remaining = employee.holiday_remaining_in_year(the_year)
      employee_engineering_days << engineering_days
      employee_engineering_days << holiday_remaining
      employee_engineering_days << (engineering_days - holiday_remaining)
      @dynamic_employees_engineering_days << employee_engineering_days
    end
    @dynamic_stats = capacity_calculator.get_stats(@dynamic_employees_engineering_days)
    @remaining_engineering_days = @dynamic_stats[:column_totals][0] || 0
  end
end

app/helpers/capacities_helper.rb
# frozen_string_literal: true

module CapacitiesHelper
  def get_column_colour(current_month, index)
    (index + 1) == current_month ? 'dark:bg-gray-800' : ''
  end

  # ["John Doe", 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
  def get_employee_series(headers, dynamic_employees_engineering_days)
    dynamic_employees_engineering_days.map do |engineering_days|
      {
        name: engineering_days[0],
        data: headers.zip(engineering_days.drop(1))
      }
    end
  end
end

app/views/capacities/_dynamic_table.html.erb
<div class="overflow-x-auto shadow-md sm:rounded-lg">
  <div class="flex flex-column sm:flex-row flex-wrap space-y-4 sm:space-y-0 items-center justify-between pb-4">
    <%= form_with(url: capacities_show_path, method: :get) do |form| %>
      <div class="flex space-x-3 items-center">
        <%= form.label :start_date, "From", class: "block text-sm text-gray-700 dark:text-gray-200 align-baseline" %>
        <%= form.date_field :start_date, value: params[:start_date] || Date.current, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        <%= form.label :end_date, "To", class: "block text-sm text-gray-700 dark:text-gray-200 align-baseline" %>
        <%= form.date_field :end_date, value: params[:end_date] || Date.current.end_of_year, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        <%= form.label :team, "Team", class: "block text-sm text-gray-700 dark:text-gray-200 align-baseline" %>
        <%= form.search_field :team, value: params[:team], class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        <%= form.label :end_date, "Committments", class: "block text-sm text-gray-700 dark:text-gray-200 align-baseline" %>
        <%= form.number_field :commitments, value: params[:commitments] || 0, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        <%= form.submit 'Calculate', class: "px-4 py-3 text-sm font-medium bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
      </div>
    <% end %>
  </div>
  <%= bar_chart get_employee_series(["Engineering Days", "Remaining holidays", "Capacities"], @dynamic_employees_engineering_days), stacked: true %>
  <table class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm dark:divide-gray-700 dark:bg-gray-900">
    <thead class="ltr:text-left rtl:text-right">
      <tr>
        <th scope="col" class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white font-bold border-b-2 border-blue-500 text-center">
          Name
        </th>
        <th scope="col" class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white font-bold border-b-2 border-green-500 text-center">
          Engineering Days
        </th>
        <th scope="col" class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white font-bold border-b-2 border-green-500 text-center">
          Remaining holidays
        </th>
        <th scope="col" class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white font-bold border-b-2 border-green-500 text-center">
          Capacities
        </th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
      <% @dynamic_employees_engineering_days.each do |employee_engineering_days| %>
        <tr class="dark:hover:bg-gray-600">
          <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white text-center">
            <%= employee_engineering_days[0].to_s.titleize %>
          </td>
          <% employee_engineering_days.drop(1).each do |days| %>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700 dark:text-gray-200 text-center">
              <%= days %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/capacities/_overall_stats.html.erb
<div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
  <div class="mx-auto max-w-3xl text-center">
    <h2 class="text-3xl font-bold text-gray-900 sm:text-4xl dark:text-white">
      Engineering Team Capacity Dashboard
    </h2>
    <p class="mt-1 text-lg text-gray-500 dark:text-gray-400">
      The current month is <%= Date.current.strftime("%B, %Y") %>
    </p>
  </div>
  <dl class="mt-6 grid grid-cols-1 gap-4 sm:mt-8 sm:grid-cols-2 lg:grid-cols-4">
    <div
      class="flex flex-col rounded-lg border border-gray-100 px-4 py-8 text-center dark:border-gray-800"
    >
      <dt class="order-last text-lg font-medium text-gray-500 dark:text-gray-400">Remaining Engineering Days</dt>
      <dd class="text-4xl font-extrabold text-blue-600 md:text-5xl"><%= @remaining_engineering_days %></dd>
    </div>
    <div
      class="flex flex-col rounded-lg border border-gray-100 px-4 py-8 text-center dark:border-gray-800"
    >
      <dt class="order-last text-lg font-medium text-gray-500 dark:text-gray-400">Remaining Holidays</dt>
      <dd class="text-4xl font-extrabold text-blue-600 md:text-5xl"><%= @holiday_remainings %></dd>
    </div>
    <div
      class="flex flex-col rounded-lg border border-gray-100 px-4 py-8 text-center dark:border-gray-800"
    >
      <dt class="order-last text-lg font-medium text-gray-500 dark:text-gray-400">Remaining Capacity</dt>
      <dd class="text-4xl font-extrabold text-blue-600 md:text-5xl"><%= @remaining_engineering_days - @holiday_remainings %></dd>
    </div>
    <div
      class="flex flex-col rounded-lg border border-gray-100 px-4 py-8 text-center dark:border-gray-800"
    >
      <dt class="order-last text-lg font-medium text-gray-500 dark:text-gray-400">vs Committments</dt>
      <dd class="text-4xl font-extrabold text-blue-600 md:text-5xl"><%= @remaining_engineering_days - @holiday_remainings - params[:commitments].to_f %></dd>
    </div>
  </dl>
</div>

app/views/capacities/_yearly_table.html.erb
<div class="overflow-x-auto shadow-md">
  <div class="">
    <%= area_chart get_employee_series(@month_names.map{|m| m.to_s.titleize}, @employees_engineering_days), stacked: true %>
  </div>
  <table
    class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm dark:divide-gray-700 dark:bg-gray-900"
  >
    <caption class="p-5 text-lg font-semibold text-left rtl:text-right text-gray-900 bg-white dark:text-white dark:bg-gray-800">
      The Monthly Engineering Capacity
      <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">It gives the summary of all employee engineering days.</p>
    </caption>
    <thead class="ltr:text-left rtl:text-right">
      <tr>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white font-bold border-b-2 border-blue-500">Name</th>
        <% @month_names.each_with_index do |month_name, index| %>
          <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white font-bold border-b-2 border-green-500 <%= get_column_colour(@current_month, index) %>">
            <%= month_name.to_s.titleize %>
          </th>
        <%  end %>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
      <% @employees_engineering_days.each do |employee_engineering_days| %>
        <tr class="dark:hover:bg-gray-600">
          <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900 dark:text-white text-center">
            <%= employee_engineering_days[0].to_s.titleize %>
          </td>
          <% employee_engineering_days.drop(1).each_with_index do |days, index| %>
            <td class="whitespace-nowrap px-4 py-2 text-gray-700 dark:text-gray-200 text-center <%= get_column_colour(@current_month, index) %>">
              <%= days %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/capacities/show.html.erb
<%= render "yearly_table" %>
<%= render "overall_stats" %>
<%= render "dynamic_table" %>